# Generated by Django 3.0.8 on 2020-08-19 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Width (mm)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Length (mm)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Height (mm)')),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Package Template',
                'verbose_name_plural': 'Package Templates',
                'ordering': ('name',),
            },
        ),
    ]
