# Generated by Django 3.0.9 on 2020-08-21 12:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200820_1619'),
    ]

    operations = [
        migrations.RemoveField(model_name='order', name='label_urls',),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(
                choices=[('dhl', 'DHL'), ('dhl', 'ExpressFreight')], default='expressfreight', max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagetemplate',
            name='weight',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (kg)'
            ),
        ),
        migrations.AlterField(
            model_name='packagetemplate',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='packagetemplate',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Length (cm)'),
        ),
        migrations.AlterField(
            model_name='packagetemplate',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Width (cm)'),
        ),
    ]
