# Generated by Django 3.1.2 on 2020-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200821_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
