# Generated by Django 3.1.3 on 2020-11-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shopify_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
