version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.4
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testing
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-py-requirements-{{ checksum "requirements.txt" }}-{{ checksum "test_requirements.txt" }}
          - grablib-files-{{ checksum "grablib.yml" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r test_requirements.txt
            grablib
            ./manage.py collectstatic --noinput --verbosity 0

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "test_requirements.txt" }}

      - save_cache:
          key: grablib-files-{{ checksum "grablib.yml" }}
          paths:
          - /salsa-verde/SalsaVerde/static/libs/

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --tb=native --cov=SalsaVerde
            flake8 SalsaVerde
            codecov --token=427a2d2a-12c2-4d27-9de9-7f173c040da4 -e=.coveragec
      - store_artifacts:
          path: test-reports
          destination: test-reports
