# Generated by Django 2.0.4 on 2018-04-18 20:23

import SalsaVerde.main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('last_logged_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Logged in')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(SalsaVerde.main.models.AddressMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=25, verbose_name='Batch Code')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('size', models.DecimalField(decimal_places=5, max_digits=25, verbose_name='Size')),
                ('type', models.CharField(choices=[('bottle', 'Bottle'), ('cap', 'Cap'), ('other', 'Container')], max_length=255, verbose_name='Container Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.TextField(blank=True, max_length=25, null=True, verbose_name='Document Type')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=25, verbose_name='Batch Code')),
                ('intake_date', models.DateTimeField(verbose_name='Intake Date')),
                ('condition', models.CharField(default='Good', max_length=25, verbose_name='Condition')),
                ('status', models.CharField(default='accept', max_length=25, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('unit', models.CharField(choices=[('kilogram', 'kg'), ('litre', 'litre')], max_length=25, verbose_name='Units')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_infusion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Infusion/Sous-vide')),
                ('date_of_bottling', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Infusion/Sous-vide')),
                ('date_of_best_before', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Best Before')),
                ('yield_quantity', models.DecimalField(decimal_places=25, max_digits=25, verbose_name='Yield Quantity (in litres)')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=25, verbose_name='Quantity')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('ingredient_types', models.ManyToManyField(related_name='product_types', to='main.IngredientType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalsaSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('form_type', models.CharField(max_length=6, verbose_name='Form Type')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone Number')),
            ],
            options={
                'abstract': False,
            },
            bases=(SalsaVerde.main.models.AddressMixin, models.Model),
        ),
        migrations.CreateModel(
            name='YieldContainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=25, verbose_name='Quantity')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('salsasheet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.SalsaSheet')),
                ('complaint_type', models.CharField(choices=[('bacteria', 'Bacteria'), ('packaging', 'Packaging'), ('foreign', 'Foreign Body'), ('other', 'Other')], max_length=255, verbose_name='Reason')),
                ('complainant_name', models.CharField(max_length=50, verbose_name='Complainant Name')),
                ('complainant_address', models.TextField(max_length=255, verbose_name='Complainant Address')),
                ('complainant_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complainant Phone')),
                ('method', models.CharField(max_length=25, verbose_name='Complainant Method')),
                ('description', models.TextField(max_length=255, verbose_name='Complainant Description')),
                ('cause', models.TextField(max_length=255, verbose_name='Complaint Cause')),
                ('corrective_action_desc', models.TextField(max_length=255, verbose_name='Corrective Action Desc')),
                ('corrective_action_date', models.DateTimeField(verbose_name='Corrective Action Taken')),
                ('complaint_reply_date', models.DateTimeField(verbose_name='Corrective Action Taken')),
            ],
            bases=('main.salsasheet',),
        ),
        migrations.CreateModel(
            name='GlassAudit',
            fields=[
                ('salsasheet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.SalsaSheet')),
                ('broken_containers', models.PositiveSmallIntegerField(verbose_name='Broken Containers')),
                ('action_taken', models.TextField(blank=True, default='', verbose_name='Action Taken')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Area')),
            ],
            bases=('main.salsasheet',),
        ),
        migrations.CreateModel(
            name='GlassBreakageReport',
            fields=[
                ('salsasheet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.SalsaSheet')),
                ('description', models.TextField(verbose_name='Breakage Details')),
                ('area_cleared', models.BooleanField(default=True, verbose_name='Area Cleared')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Area')),
            ],
            bases=('main.salsasheet',),
        ),
        migrations.CreateModel(
            name='PlasterReport',
            fields=[
                ('salsasheet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.SalsaSheet')),
                ('plaster_check_time', models.DateTimeField(verbose_name='Plaster Check Time')),
            ],
            bases=('main.salsasheet',),
        ),
        migrations.AddField(
            model_name='salsasheet',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salsa_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='product_ingredients',
            field=models.ManyToManyField(related_name='products', to='main.ProductIngredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.ProductType'),
        ),
        migrations.AddField(
            model_name='product',
            name='yield_containers',
            field=models.ManyToManyField(related_name='products', to='main.YieldContainers'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='main.IngredientType'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='intake_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='main.Supplier'),
        ),
        migrations.AddField(
            model_name='container',
            name='container_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ContainerType'),
        ),
        migrations.AddField(
            model_name='user',
            name='health_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_hq', to='main.Document'),
        ),
        migrations.AddField(
            model_name='user',
            name='rtw_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_rtwq', to='main.Document'),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_induction_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_sip', to='main.Document'),
        ),
        migrations.AddField(
            model_name='user',
            name='training_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_tr', to='main.Document'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='plasterreport',
            name='plaster_check_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plasterreport',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaster_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='glassaudit',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glass_audits', to='main.Container'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='affected_product',
            field=models.ManyToManyField(related_name='complaints', to='main.Product'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
