# Generated by Django 2.0.4 on 2018-09-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('ingredient_type__name',), 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='ingredienttype',
            options={'ordering': ('name',), 'verbose_name': 'Ingredient Type', 'verbose_name_plural': 'Ingredients Types'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',), 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AddField(
            model_name='container',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='document',
            name='focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focused_documents', to=settings.AUTH_USER_MODEL, verbose_name='Associated with'),
        ),
    ]
