# Generated by Django 2.0.4 on 2018-09-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180904_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=25, verbose_name='SKU Code', null=True, blank=True)),
                ('bar_code', models.CharField(max_length=40, verbose_name='Bar Code', null=True, blank=True)),
                ('size', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Container Size in litres')),
            ],
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='sku_code',
        ),
        migrations.AddField(
            model_name='producttypesize',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type_sizes', to='main.ProductType'),
        ),
    ]
