# Generated by Django 2.1.7 on 2019-03-25 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190112_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(
                choices=[('infused', 'Infused'), ('bottled', 'Bottled')],
                default='bottled',
                max_length=25,
                verbose_name='Stage',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='batch_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Batch Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_best_before',
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Best Before'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_bottling',
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Bottling'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='yield_quantity',
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=25, null=True, verbose_name='Yield Quantity (in litres)'
            ),
        ),
    ]
