# Generated by Django 3.0.7 on 2020-07-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190513_1821'),
    ]

    operations = [
        migrations.AddField(model_name='company', name='website', field=models.CharField(blank=True, max_length=255),),
    ]
