# Generated by Django 3.0.8 on 2020-08-18 15:41

import datetime
import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                (
                    'last_logged_in',
                    models.DateTimeField(
                        default=datetime.datetime(2018, 1, 1, 0, 0, tzinfo=utc), verbose_name='Last Logged in'
                    ),
                ),
                ('street', models.TextField(blank=True, null=True, verbose_name='Street Address')),
                ('town', models.CharField(blank=True, max_length=50, null=True, verbose_name='Town')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postcode')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
            ],
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users',},
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('website', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=25, verbose_name='Batch Code')),
                ('condition', models.CharField(default='Good', max_length=25, verbose_name='Condition')),
                (
                    'intake_quality_check',
                    models.BooleanField(
                        default=False, help_text='Goods are free from damage and pests', verbose_name='Accept goods'
                    ),
                ),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=25, verbose_name='Quantity')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
            ],
            options={'verbose_name': 'Container', 'verbose_name_plural': 'Containers',},
        ),
        migrations.CreateModel(
            name='GoodsIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('intake_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Intake date')),
                (
                    'intake_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Intake Recipient',
                    ),
                ),
            ],
            options={'abstract': False,},
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=25, verbose_name='Batch Code')),
                ('condition', models.CharField(default='Good', max_length=25, verbose_name='Condition')),
                (
                    'intake_quality_check',
                    models.BooleanField(
                        default=False, help_text='Goods are free from damage and pests', verbose_name='Accept goods'
                    ),
                ),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=25, verbose_name='Quantity')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                (
                    'goods_intake',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ingredients',
                        to='stock.GoodsIntake',
                        verbose_name='Goods Intake',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ('ingredient_type__name',),
            },
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                (
                    'unit',
                    models.CharField(
                        choices=[('kilogram', 'kg'), ('litre', 'litre')],
                        help_text='Ingredient is measured in?',
                        max_length=25,
                        verbose_name='Units',
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='stock.Company', verbose_name='Company'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ingredient Type',
                'verbose_name_plural': 'Ingredients Types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'date_of_infusion',
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Infusion/Sous-vide'),
                ),
                (
                    'date_of_bottling',
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Bottling'
                    ),
                ),
                (
                    'date_of_best_before',
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Best Before'
                    ),
                ),
                (
                    'yield_quantity',
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=25,
                        null=True,
                        verbose_name='Yield Quantity (in litres)',
                    ),
                ),
                ('batch_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Batch Code')),
                (
                    'status',
                    models.CharField(
                        choices=[('infused', 'Infused'), ('bottled', 'Bottled')], max_length=25, verbose_name='Stage'
                    ),
                ),
                ('batch_code_applied', models.BooleanField(default=False, verbose_name='Batch code applied')),
                ('best_before_applied', models.BooleanField(default=False, verbose_name='Best before applied')),
                (
                    'quality_check_successful',
                    models.BooleanField(default=False, verbose_name='Quality check successful'),
                ),
            ],
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products',},
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                (
                    'code',
                    models.CharField(
                        help_text='2 or 3 letter code for batch code creation', max_length=3, verbose_name='Code'
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='stock.Company', verbose_name='Company'
                    ),
                ),
                (
                    'ingredient_types',
                    models.ManyToManyField(
                        related_name='product_types', to='stock.IngredientType', verbose_name='Ingredients'
                    ),
                ),
            ],
            options={'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types', 'ordering': ('name',),},
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('website', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='YieldContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=25, verbose_name='Quantity')),
                (
                    'container',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='yield_containers',
                        to='stock.Container',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='yield_containers',
                        to='stock.Product',
                        verbose_name='Product',
                    ),
                ),
            ],
            options={'abstract': False,},
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('street', models.TextField(blank=True, null=True, verbose_name='Street Address')),
                ('town', models.CharField(blank=True, max_length=50, null=True, verbose_name='Town')),
                ('county', models.CharField(blank=True, max_length=50, null=True, verbose_name='County')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postcode')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=65, null=True, verbose_name='Email')),
                ('main_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main Contact')),
                (
                    'contact_phone',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Phone'),
                ),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Number')),
                (
                    'company_number',
                    models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Number'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='stock.Company', verbose_name='Company'
                    ),
                ),
            ],
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers', 'ordering': ('name',),},
        ),
        migrations.CreateModel(
            name='ProductTypeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='SKU Code')),
                ('bar_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='Bar Code')),
                ('size', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Container Size in litres')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                (
                    'product_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='product_type_sizes',
                        to='stock.ProductType',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=25, verbose_name='Quantity')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Ingredient')),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='product_ingredients',
                        to='stock.Product',
                        verbose_name='Product',
                    ),
                ),
            ],
            options={'abstract': False,},
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='stock.ProductType',
                verbose_name='Product',
            ),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ingredients',
                to='stock.IngredientType',
                verbose_name='Ingredient Type',
            ),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ingredients',
                to='stock.Supplier',
                verbose_name='Supplier',
            ),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                (
                    'type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('com1', 'COM1 - Complaint Summary'),
                            ('com2', 'COM2 - Complaint Log'),
                            ('gl01', 'GL01 - Glass Audit'),
                            ('gl02', 'GL02 - Glass Breakage Report'),
                            ('int1', 'INT1 - Intake of Goods'),
                            ('nc01', 'NC01 - Non Conformity Report'),
                            ('pla01', 'PLA01 - Plaster Log'),
                            ('st01', 'ST01 - Staff Health Questionnaire'),
                            ('st02', 'ST02 - Return to Work Questionnaire'),
                            ('st03', 'ST03 - Induction Log'),
                            ('st04', 'ST04 - Staff Training Record'),
                            ('sup01', 'SUP01 - Raw Materials Suppliers'),
                            ('sup02', 'SUP02 - Packaging Suppliers'),
                            ('sup03', 'SUP03 - Service Suppliers'),
                            ('sup04', 'SUP04 - Supplier Self Audit'),
                            ('tra01', 'TRA01 - Traceability'),
                            ('vis01', 'VIS01 - Visitor Questionnaire'),
                        ],
                        max_length=6,
                        null=True,
                        verbose_name='Salsa Form Type',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        blank=True, max_length=256, storage=django.core.files.storage.FileSystemStorage(), upload_to=''
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='documents',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Author',
                    ),
                ),
                (
                    'focus',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='focused_documents',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Associated with',
                    ),
                ),
                (
                    'goods_intake',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='documents',
                        to='stock.GoodsIntake',
                        verbose_name='Intake of Goods',
                    ),
                ),
                (
                    'supplier',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='documents',
                        to='stock.Supplier',
                        verbose_name='Linked Supplier',
                    ),
                ),
            ],
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents',},
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                (
                    'size',
                    models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True, verbose_name='Size'),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('bottle', 'Bottle'), ('cap', 'Cap'), ('other', 'Container')],
                        default='bottle',
                        max_length=255,
                        verbose_name='Container Type',
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='stock.Company', verbose_name='Company'
                    ),
                ),
            ],
            options={'verbose_name': 'Container Type', 'verbose_name_plural': 'Container Types',},
        ),
        migrations.AddField(
            model_name='container',
            name='container_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='containers',
                to='stock.ContainerType',
                verbose_name='Container',
            ),
        ),
        migrations.AddField(
            model_name='container',
            name='goods_intake',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='containers',
                to='stock.GoodsIntake',
                verbose_name='Goods Intake',
            ),
        ),
        migrations.AddField(
            model_name='container',
            name='supplier',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='containers',
                to='stock.Supplier',
                verbose_name='Supplier',
            ),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='stock.Company', verbose_name='Company'
                    ),
                ),
            ],
            options={'abstract': False,},
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='stock.Company', verbose_name='Company'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                related_name='user_set',
                related_query_name='user',
                to='auth.Group',
                verbose_name='groups',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(
                blank=True,
                help_text='Specific permissions for this user.',
                related_name='user_set',
                related_query_name='user',
                to='auth.Permission',
                verbose_name='user permissions',
            ),
        ),
        migrations.CreateModel(
            name='PlasterReport',
            fields=[
                (
                    'document_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='stock.Document',
                    ),
                ),
                ('plaster_check_time', models.DateTimeField(verbose_name='Plaster Check Time')),
                (
                    'plaster_check_employee',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'recipient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plaster_reports',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('stock.document',),
        ),
        migrations.CreateModel(
            name='GlassBreakageReport',
            fields=[
                (
                    'document_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='stock.Document',
                    ),
                ),
                ('description', models.TextField(verbose_name='Breakage Details')),
                ('area_cleared', models.BooleanField(default=True, verbose_name='Area Cleared')),
                (
                    'breakage_area',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Area'
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('stock.document',),
        ),
        migrations.CreateModel(
            name='GlassAudit',
            fields=[
                (
                    'document_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='stock.Document',
                    ),
                ),
                ('broken_containers', models.PositiveSmallIntegerField(verbose_name='Broken Containers')),
                ('action_taken', models.TextField(blank=True, default='', verbose_name='Action Taken')),
                (
                    'audited_area',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Area'
                    ),
                ),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Container')),
            ],
            options={'abstract': False,},
            bases=('stock.document',),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                (
                    'document_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='stock.Document',
                    ),
                ),
                (
                    'complaint_type',
                    models.CharField(
                        choices=[
                            ('bacteria', 'Bacteria'),
                            ('packaging', 'Packaging'),
                            ('foreign', 'Foreign Body'),
                            ('other', 'Other'),
                        ],
                        max_length=255,
                        verbose_name='Reason',
                    ),
                ),
                ('complainant_name', models.CharField(max_length=50, verbose_name='Complainant Name')),
                ('complainant_address', models.TextField(max_length=255, verbose_name='Complainant Address')),
                (
                    'complainant_phone',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Complainant Phone'),
                ),
                ('method', models.CharField(max_length=25, verbose_name='Complainant Method')),
                ('description', models.TextField(max_length=255, verbose_name='Complainant Description')),
                ('cause', models.TextField(max_length=255, verbose_name='Complaint Cause')),
                ('corrective_action_desc', models.TextField(max_length=255, verbose_name='Corrective Action Desc')),
                ('corrective_action_date', models.DateTimeField(verbose_name='Corrective Action Taken')),
                ('complaint_reply_date', models.DateTimeField(verbose_name='Corrective Action Taken')),
                ('affected_product', models.ManyToManyField(related_name='complaints', to='stock.Product')),
                (
                    'investigator',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('stock.document',),
        ),
    ]
