# Generated by Django 3.0.9 on 2020-08-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product', name='finished', field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
    ]
