# Generated by Django 3.0.9 on 2020-08-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_type__name',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
