# Generated by Django 2.0.4 on 2018-09-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20180904_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='SKU Code')),
                ('bar_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='Bar Code')),
                ('size', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Container Size in litres')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('name',), 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.RemoveField(model_name='producttype', name='sku_code',),
        migrations.AddField(
            model_name='producttypesize',
            name='product_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='product_type_sizes', to='stock.ProductType'
            ),
        ),
    ]
