# Generated by Django 3.0.9 on 2020-08-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200821_1211'),
        ('stock', '0003_auto_20200820_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='labels',
                to='orders.Order',
            ),
        ),
    ]
