# Generated by Django 4.2.9 on 2024-03-14 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0004_document_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Packaging', 'verbose_name_plural': 'Packaging'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date_created'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={
                'ordering': ('ingredient_type__name',),
                'verbose_name': 'Raw Ingredient',
                'verbose_name_plural': 'Raw Ingredients',
            },
        ),
        migrations.RemoveField(
            model_name='container',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='document',
            name='goods_intake',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='condition',
        ),
        migrations.AddField(
            model_name='container',
            name='intake_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Intake date'),
        ),
        migrations.AddField(
            model_name='container',
            name='intake_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Intake Notes'),
        ),
        migrations.AddField(
            model_name='container',
            name='intake_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Intake Recipient',
            ),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='intake_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Intake date'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='intake_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Intake Notes'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='intake_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Intake Recipient',
            ),
        ),
        migrations.AddField(
            model_name='yieldcontainer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='yieldcontainer',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='containers',
                to='stock.containertype',
                verbose_name='Packaging type',
            ),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ingredients',
                to='stock.ingredienttype',
                verbose_name='Raw ingredient type',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_infusion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Production'),
        ),
        migrations.AlterField(
            model_name='product',
            name='yield_quantity',
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=25, null=True, verbose_name='Yield Quantity'
            ),
        ),
    ]
