# Generated by Django 4.2.9 on 2024-02-04 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0004_document_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='goods_intake',
        ),
        migrations.RemoveField(
            model_name='document',
            name='goods_intake',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='goods_intake',
        ),
        migrations.AddField(
            model_name='container',
            name='intake_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Intake date'),
        ),
        migrations.AddField(
            model_name='container',
            name='intake_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Intake Notes'),
        ),
        migrations.AddField(
            model_name='container',
            name='intake_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Intake Recipient',
            ),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='intake_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Intake date'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='intake_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Intake Notes'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='intake_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Intake Recipient',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_infusion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Production'),
        ),
        migrations.DeleteModel(
            name='GoodsIntake',
        ),
    ]
