# Generated by Django 4.2.9 on 2024-03-14 19:27

from django.db import migrations


def migrate_intake_user(apps, schema_editor):
    Container = apps.get_model('stock', 'Container')
    Ingredient = apps.get_model('stock', 'Ingredient')
    GoodsIntake = apps.get_model('stock', 'GoodsIntake')
    for gi in GoodsIntake.objects.all():
        Container.objects.filter(goods_intake=gi).update(intake_user=gi.intake_user, intake_date=gi.intake_date)
        Ingredient.objects.filter(goods_intake=gi).update(intake_user=gi.intake_user, intake_date=gi.intake_date)


class Migration(migrations.Migration):
    dependencies = [('stock', '0005_alter_container_options_alter_document_options_and_more')]

    operations = [
        migrations.RunPython(migrate_intake_user),
    ]
