# Generated by Django 4.2.9 on 2024-02-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock', '0005_remove_container_goods_intake_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='condition',
        ),
        migrations.AlterField(
            model_name='product',
            name='yield_quantity',
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=25, null=True, verbose_name='Yield Quantity'
            ),
        ),
    ]
