# Generated by Django 3.1.2 on 2020-10-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200821_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shopify_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='shopify_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='shopify_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='shopify_webhook_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
