# Generated by Django 3.1.2 on 2020-11-03 11:54

from django.db import migrations, models


def update_users(apps, schema):
    User = apps.get_model('company', 'user')
    User.objects.update(administrator=True)


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201026_1524'),
    ]

    operations = [
        migrations.AddField(model_name='user', name='administrator', field=models.BooleanField(default=False)),
        migrations.RunPython(update_users),
    ]
