# Generated by Django 4.2.9 on 2024-02-21 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0005_auto_20201114_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
